# Generated by Django 6.0.4 on 2026-05-06 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_titulo', models.CharField(default='COSFA SUPERCAMPEONES', max_length=200)),
                ('banner_subtitulo', models.CharField(default='Torneo Escolar Intercolegiado', max_length=200)),
                ('mensaje_bienvenida', models.TextField(blank=True, default='¡Bienvenidos al torneo!')),
                ('mostrar_estadisticas', models.BooleanField(default=True)),
                ('mostrar_tabla', models.BooleanField(default=True)),
                ('gemini_api_key', models.CharField(blank=True, default='', max_length=200, verbose_name='Gemini API Key')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carrusel/')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ReglaDeporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(choices=[('futbol', 'Fútbol'), ('baloncesto', 'Baloncesto'), ('voleibol', 'Voleibol')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('documento', models.FileField(blank=True, help_text='PDF o Word con el reglamento completo', null=True, upload_to='reglas/')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('T', 'Transición'), ('1', '1°'), ('2', '2°'), ('3', '3°'), ('4', '4°'), ('5', '5°'), ('6', '6°'), ('7', '7°'), ('8', '8°'), ('9', '9°'), ('10', '10°'), ('11', '11°'), ('P', 'Profesores')], max_length=3)),
                ('grupo', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('pais', models.CharField(blank=True, max_length=60, null=True)),
                ('bandera', models.ImageField(blank=True, null=True, upload_to='banderas/')),
            ],
            options={
                'ordering': ['grado', 'grupo'],
                'unique_together': {('grado', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(choices=[('futbol', 'Fútbol'), ('baloncesto', 'Baloncesto'), ('voleibol', 'Voleibol')], max_length=20)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Mixto')], default='X', max_length=1)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipos/')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.grado')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B')], max_length=1)),
                ('ciclo', models.CharField(choices=[('I', 'Ciclo I'), ('II', 'Ciclo II'), ('III', 'Ciclo III'), ('IV', 'Ciclo IV')], max_length=3)),
                ('deporte', models.CharField(choices=[('futbol', 'Fútbol'), ('baloncesto', 'Baloncesto'), ('voleibol', 'Voleibol')], max_length=20)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Mixto')], default='X', max_length=1)),
                ('fase_grupos_terminada', models.BooleanField(default=False)),
                ('equipos', models.ManyToManyField(blank=True, related_name='grupos_torneo', to='core.equipo')),
            ],
            options={
                'unique_together': {('nombre', 'ciclo', 'deporte', 'genero')},
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ti', models.CharField(max_length=20, unique=True, verbose_name='T.I.')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('grado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='core.grado')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='capitan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitan_de', to='core.jugador'),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_local', models.IntegerField(default=0)),
                ('puntos_visitante', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('fase', models.CharField(choices=[('grupos', 'Fase de Grupos'), ('tercer_puesto', 'Tercer Puesto'), ('final', 'Final')], default='grupos', max_length=20)),
                ('jugado', models.BooleanField(default=False)),
                ('deporte', models.CharField(choices=[('futbol', 'Fútbol'), ('baloncesto', 'Baloncesto'), ('voleibol', 'Voleibol')], default='futbol', max_length=20)),
                ('ciclo', models.CharField(choices=[('I', 'Ciclo I'), ('II', 'Ciclo II'), ('III', 'Ciclo III'), ('IV', 'Ciclo IV')], default='I', max_length=3)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Mixto')], default='X', max_length=1)),
                ('link_facebook', models.URLField(blank=True, help_text='Link al video del partido en Facebook', null=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='core.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='core.equipo')),
                ('grupo_torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='core.grupotorneo')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gol', 'Gol')], default='gol', max_length=20)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.equipo')),
                ('asistente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_dadas', to='core.jugador')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.partido')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_camiseta', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.jugador')),
            ],
            options={
                'unique_together': {('jugador', 'equipo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together={('grado', 'deporte', 'genero')},
        ),
    ]
