# Generated by Django 6.0.5 on 2026-05-10 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetVoleibol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_set', models.IntegerField()),
                ('puntos_local', models.IntegerField(default=0)),
                ('puntos_visita', models.IntegerField(default=0)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='core.partido')),
            ],
            options={
                'ordering': ['numero_set'],
                'unique_together': {('partido', 'numero_set')},
            },
        ),
    ]
