# Generated by Django 6.0.5 on 2026-05-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setvoleibol'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorneoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Torneo', max_length=100)),
                ('año', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('resumen_json', models.TextField(default='{}', help_text='JSON con campeones, goleadores, etc.')),
            ],
            options={
                'ordering': ['-año', '-creado'],
            },
        ),
    ]
