# Generated by Django 6.0.5 on 2026-05-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_torneohistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaisParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('emoji', models.CharField(blank=True, default='🌍', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'País Participante',
                'verbose_name_plural': 'Países Participantes',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
