from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('inicio/', views.vista_usuario, name='vista_usuario'),
    path('panel/paises/', views.admin_paises, name='admin_paises'),
    path('panel/paises/guardar/', views.guardar_paises_config, name='guardar_paises_config'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('buscar/', views.buscar_jugadores, name='buscar'),
    path('jugador/<int:pk>/', views.perfil_jugador, name='perfil_jugador'),
    path('partido/<int:pk>/', views.partido_detalle, name='partido_detalle'),
    path('grado/<int:pk>/', views.vista_grado, name='vista_grado'),
    path('partidos/', views.partidos_view, name='partidos_view'),
    path('estadisticas/', views.estadisticas, name='estadisticas'),
    path('tabla/', views.tabla_posiciones, name='tabla_posiciones'),
    path('reglas/', views.reglas, name='reglas'),
    path('historial/', views.historial_torneos, name='historial_torneos'),
    path('panel/horario/', views.admin_horario_semanal, name='admin_horario_semanal'),
    path('chat/', views.chatbot_view, name='chatbot'),
    path('chat/api/', views.chatbot_api, name='chatbot_api'),
    # Admin
    path('panel/', views.admin_dashboard, name='admin_dashboard'),
    path('panel/grados/', views.admin_grados, name='admin_grados'),
    path('panel/grados/crear/', views.admin_grado_crear, name='admin_grado_crear'),
    path('panel/grados/<int:pk>/', views.admin_grado_detalle, name='admin_grado_detalle'),
    path('panel/grados/<int:pk>/editar/', views.admin_grado_editar, name='admin_grado_editar'),
    path('panel/grados/<int:pk>/eliminar/', views.admin_grado_eliminar, name='admin_grado_eliminar'),
    path('panel/grados/paises/', views.sorteo_paises, name='sorteo_paises'),
    # Alias con singular por compatibilidad con links existentes
    path('panel/grado/paises/', views.sorteo_paises),
    path('panel/equipos/<int:pk>/editar/', views.admin_equipo_editar, name='admin_equipo_editar'),
    path('panel/jugadores/', views.admin_jugadores, name='admin_jugadores'),
    path('panel/jugadores/crear/', views.admin_jugador_crear, name='admin_jugador_crear'),
    path('panel/grados/<int:grado_pk>/inscribir-jugador/', views.admin_jugador_crear, name='admin_jugador_crear_en_grado'),
    path('panel/jugadores/<int:pk>/editar/', views.admin_jugador_editar, name='admin_jugador_editar'),
    path('panel/jugadores/<int:pk>/eliminar/', views.admin_jugador_eliminar, name='admin_jugador_eliminar'),
    path('panel/jugadores/insc/<int:pk>/eliminar/', views.admin_insc_eliminar, name='admin_insc_eliminar'),
    path('panel/jugadores/equipos-por-grado/', views.equipos_por_grado, name='equipos_por_grado'),
    path('panel/partidos/', views.admin_partidos, name='admin_partidos'),
    path('panel/partidos/crear/', views.admin_partido_crear, name='admin_partido_crear'),
    path('panel/partidos/<int:pk>/editar/', views.admin_partido_editar, name='admin_partido_editar'),
    path('panel/partidos/<int:pk>/eliminar/', views.admin_partido_eliminar, name='admin_partido_eliminar'),
    path('panel/sorteo/', views.admin_sorteo_grupos, name='admin_sorteo_grupos'),
    path('panel/reglas/', views.admin_reglas, name='admin_reglas'),
    path('panel/reglas/crear/', views.admin_regla_form, name='admin_regla_crear'),
    path('panel/reglas/<int:pk>/editar/', views.admin_regla_form, name='admin_regla_editar'),
    path('panel/reglas/<int:pk>/eliminar/', views.admin_regla_eliminar, name='admin_regla_eliminar'),
    path('panel/carrusel/', views.admin_carrusel, name='admin_carrusel'),
    path('panel/carrusel/crear/', views.admin_carrusel_crear, name='admin_carrusel_crear'),
    path('panel/carrusel/<int:pk>/editar/', views.admin_carrusel_editar, name='admin_carrusel_editar'),
    path('panel/carrusel/<int:pk>/eliminar/', views.admin_carrusel_eliminar, name='admin_carrusel_eliminar'),
    path('panel/config/', views.admin_configuracion, name='admin_configuracion'),
    path('panel/cerrar-torneo/', views.admin_cerrar_torneo, name='admin_cerrar_torneo'),
    path('panel/finalizar-registro/', views.admin_finalizar_registro, name='admin_finalizar_registro'),
]
